In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

# 1. Create

In [3]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [4]:
data

array([[[0.26627053, 0.53282023, 0.43582756, 0.09682948],
        [0.98588057, 0.61907291, 0.15630143, 0.42345493],
        [0.85923674, 0.94635698, 0.67835361, 0.24457791]],

       [[0.83069905, 0.8001238 , 0.54664149, 0.70031627],
        [0.62295321, 0.54339334, 0.28347356, 0.63100938],
        [0.72604727, 0.1329136 , 0.87568866, 0.78436664]]])

In [5]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [7]:
type(arr)

numpy.ndarray

# 2. Read

In [8]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [9]:
types

dtype('float64')

In [10]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [11]:
singleval

0.2662705347462502

In [12]:
data

array([[[0.26627053, 0.53282023, 0.43582756, 0.09682948],
        [0.98588057, 0.61907291, 0.15630143, 0.42345493],
        [0.85923674, 0.94635698, 0.67835361, 0.24457791]],

       [[0.83069905, 0.8001238 , 0.54664149, 0.70031627],
        [0.62295321, 0.54339334, 0.28347356, 0.63100938],
        [0.72604727, 0.1329136 , 0.87568866, 0.78436664]]])

# 3. Update

In [13]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [14]:
list2

array([0.3063025 , 0.94391284, 0.65111057, 0.33879812, 0.77313165,
       0.73131452, 0.29678173, 0.92743002, 0.6631745 , 0.33332028])

In [15]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [16]:
dot

3.659055981791086

In [17]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [18]:
maxs

0.9687578112470048

In [19]:
data

array([[[0.26627053, 0.53282023, 0.43582756, 0.09682948],
        [0.98588057, 0.61907291, 0.15630143, 0.42345493],
        [0.85923674, 0.94635698, 0.67835361, 0.24457791]],

       [[0.83069905, 0.8001238 , 0.54664149, 0.70031627],
        [0.62295321, 0.54339334, 0.28347356, 0.63100938],
        [0.72604727, 0.1329136 , 0.87568866, 0.78436664]]])

In [20]:
data[0][0][0] = 700

In [21]:
data

array([[[7.00000000e+02, 5.32820230e-01, 4.35827560e-01, 9.68294765e-02],
        [9.85880566e-01, 6.19072909e-01, 1.56301427e-01, 4.23454928e-01],
        [8.59236739e-01, 9.46356976e-01, 6.78353609e-01, 2.44577914e-01]],

       [[8.30699052e-01, 8.00123800e-01, 5.46641486e-01, 7.00316271e-01],
        [6.22953207e-01, 5.43393337e-01, 2.83473561e-01, 6.31009377e-01],
        [7.26047269e-01, 1.32913597e-01, 8.75688659e-01, 7.84366638e-01]]])

In [22]:
data.sort()
data

array([[[9.68294765e-02, 4.35827560e-01, 5.32820230e-01, 7.00000000e+02],
        [1.56301427e-01, 4.23454928e-01, 6.19072909e-01, 9.85880566e-01],
        [2.44577914e-01, 6.78353609e-01, 8.59236739e-01, 9.46356976e-01]],

       [[5.46641486e-01, 7.00316271e-01, 8.00123800e-01, 8.30699052e-01],
        [2.83473561e-01, 5.43393337e-01, 6.22953207e-01, 6.31009377e-01],
        [1.32913597e-01, 7.26047269e-01, 7.84366638e-01, 8.75688659e-01]]])

In [23]:
print(data.shape)

(2, 3, 4)


In [24]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [25]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [26]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [27]:
data

array([[[9.68294765e-02, 4.35827560e-01, 5.32820230e-01, 7.00000000e+02,
         1.56301427e-01, 4.23454928e-01],
        [6.19072909e-01, 9.85880566e-01, 2.44577914e-01, 6.78353609e-01,
         8.59236739e-01, 9.46356976e-01]],

       [[5.46641486e-01, 7.00316271e-01, 8.00123800e-01, 8.30699052e-01,
         2.83473561e-01, 5.43393337e-01],
        [6.22953207e-01, 6.31009377e-01, 1.32913597e-01, 7.26047269e-01,
         7.84366638e-01, 8.75688659e-01]]])

In [28]:
np.delete(data, 0, axis=1)

array([[[0.61907291, 0.98588057, 0.24457791, 0.67835361, 0.85923674,
         0.94635698]],

       [[0.62295321, 0.63100938, 0.1329136 , 0.72604727, 0.78436664,
         0.87568866]]])

In [29]:
np.save("new array", data)

In [30]:
test = np.load("new array.npy")

In [31]:
test

array([[[9.68294765e-02, 4.35827560e-01, 5.32820230e-01, 7.00000000e+02,
         1.56301427e-01, 4.23454928e-01],
        [6.19072909e-01, 9.85880566e-01, 2.44577914e-01, 6.78353609e-01,
         8.59236739e-01, 9.46356976e-01]],

       [[5.46641486e-01, 7.00316271e-01, 8.00123800e-01, 8.30699052e-01,
         2.83473561e-01, 5.43393337e-01],
        [6.22953207e-01, 6.31009377e-01, 1.32913597e-01, 7.26047269e-01,
         7.84366638e-01, 8.75688659e-01]]])